numero = input('Digite um número entre 0 e 9999: ')
numero = numero.zfill(4)
print('unidade: {}'.format(numero[3]))
print('dezena: {}'.format(numero[2]))
print('centena: {}'.format(numero[1]))
print('milhar: {}'.format(numero[0]))
